name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container_image }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        sourcemod-version: [1.12-dev, master]
        include:
          - target-archs: x86,x86_64

          - os: ubuntu-latest
            container_image: ghcr.io/alliedmodders/build-containers/debian11:latest
    steps:
      # Largely a workaround for issue where github.workspace doesn't match $GITHUB_WORKSPACE
      # in containerized jobs. See https://github.com/actions/runner/issues/2058
      - name: Resolve paths
        id: path_helper
        shell: bash
        run: |
          echo "dependencies=$GITHUB_WORKSPACE/dependencies" >> $GITHUB_OUTPUT
          echo "basedir=$GITHUB_WORKSPACE" >> $GITHUB_OUTPUT

      - name: Set up Python
        if: runner.os == 'Windows'
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.13

      - name: Setup AMBuild
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/alliedmodders/ambuild

      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          path: extension

      - name: Fetch SourceMod ${{ matrix.sourcemod-version }}
        uses: actions/checkout@v7.0.1
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sourcemod-version }}
          path: sourcemod
          submodules: recursive

      - name: Build
        working-directory: extension
        shell: bash
        run: |
          mkdir build && cd build
          perl ../curl/lib/mk-ca-bundle.pl
          python ../configure.py --enable-optimize --targets=${{ matrix.target-archs }}
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ runner.os }}-${{ matrix.sourcemod-version }}
          path: extension/build/package


  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8.0.1

      - name: Package
        run: |
          version=`echo $GITHUB_REF | sed "s/refs\/tags\///"`
          7z a sm-ripext-${version}-linux.zip ./Linux/*
          7z a sm-ripext-${version}-windows.zip ./Windows/*

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: '*.zip'
          file_glob: true
